[package]
name = "server"
version = "0.1.0"
authors = ["Min4Builder <lieks124@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1"
mio = "0.6"
flate2 = "1.0"
noise = "0.5"

[profile.dev]
opt-level = 2

[profile.release]
debug = true
lto = true

